networks:
  jsramverk:
    driver: bridge

services:
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "1337:1337"
    networks:
      - jsramverk
    env_file:
      - backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - jsramverk
    env_file:
      - frontend/.env
